create table SPRING_SESSION_ATTRIBUTES
(
    SESSION_PRIMARY_ID CHAR(36),
    ATTRIBUTE_NAME     VARCHAR(200),
    ATTRIBUTE_BYTES    BLOB,
    SESSIONPRIMARYID   INTEGER not null,
    ATTRIBUTEBYTES     BLOB,
    ATTRIBUTENAME      VARCHAR(255)
);

